<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 16.08.2017
 * Time: 15:30
 */

namespace App\Services;


use App\Repositories\CategoryRepository;
use App\Repositories\ProductRepository;

/**
 * Class ErrorService
 * @package App\Services
 */
class ErrorService extends LayoutService
{
    /**
     * ErrorService constructor.
     * @param CategoryRepository $categoryRepository
     * @param ProductRepository $productRepository
     */
    public function __construct(CategoryRepository $categoryRepository, ProductRepository $productRepository)
    {
        parent::__construct($categoryRepository, $productRepository);
    }

    /**
     * @param $model
     */
    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub

        $this->fillMeta($model);
    }

    /**
     * fill meta tags
     * @param $model
     */
    private function fillMeta($model)
    {
        $model->title = trans('meta.error_page_title');
    }
}